version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - '5000:5000'
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    restart: always

networks:
  default:
    driver: bridge
